# generated by datamodel-codegen:
#   filename:  invoice.json
#   timestamp: 2024-09-20T13:49:33+00:00

from __future__ import annotations

from datetime import date
from typing import List

from pydantic import BaseModel


class Company(BaseModel):
    name: str
    address: str
    postalCode: str
    city: str
    country: str
    vatNumber: str


class Item(BaseModel):
    description: str
    quantity: float
    price: float
    vat: float
    totalInclVat: float


class Invoice(BaseModel):
    invoiceNumber: str
    invoiceDate: str
    dueDate: str
    customerVatNumber: str
    items: List[Item]
    taxableAmount: str
    vatAmount: str
    totalAmount: str


class Model(BaseModel):
    company: Company
    invoice: Invoice
